# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bonnus SDK Example Objective C' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bonnus SDK Example Objective C
  pod 'ObjectMapper'

end
